"""Add ExamResult model

Revision ID: 567aca79260b
Revises: f121b83e2cf3
Create Date: 2025-06-25 09:08:57.313457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '567aca79260b'
down_revision = 'f121b83e2cf3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exam_result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('total_questions', sa.Integer(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.Column('results_detail', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exam_result')
    # ### end Alembic commands ###
