"""empty message

Revision ID: 93b9abb76ec8
Revises: f8cc85e1e5d4
Create Date: 2025-06-25 16:13:21.578891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93b9abb76ec8'
down_revision = 'f8cc85e1e5d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('question_type', sa.String(length=50), nullable=False, server_default='multiple_choice'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_column('question_type')

    # ### end Alembic commands ###
