from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
# これらは実際のファイルの値に合わせてください
revision = 'b6e6590815ba' # 例: エラーログにあったリビジョンID
down_revision = '19d909b29f36' # このマイグレーションの直前のリビジョンID (なければNone)
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), 
                                      nullable=False, 
                                      server_default=sa.false())) # ← server_default を追加！
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_admin')
    # ### end Alembic commands ###